[package]
name = "models-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
prettyplease = "0.2"
schemars = "0.8"
serde_json = "1.0"
typify = "0.5.0"
syn = "2.0"
serde = "1.0.228"

[build-dependencies]
prettyplease = "0.2"
schemars = "0.8"
serde_json = "1.0"
typify = "0.5.0"
syn = "2.0"
